### ISSUE TITLE
Getting teleported to a weird zoomed out version of Station of Serenity and Roxas' room

### ISSUE THREAD

**Issue by gregest** [TopazTK/KH-ReFixed#46] opened 2022-06-17 16:33 UTC
**Re:Fixed Version:**
v2.90 STABLE

**Game in Question:**
KH2

**Bug Description:**
I was going through roxas' intro like you would normally and I got to the part where you finally go into the mansion, skipped cutscene as always and it somehow put me inside Station of Serenity but extremely zoomed out where I couldn't do anything so I alt f4'd the game, on startup now there was a save on slot 99 that I loaded and it put me inside Roxas' room, happened every time I tried to go to the mansion, fixed it by reverting to the normal exe 

**Reproduction Steps:**
Not sure? I didn't do anything special besides just go to the mansion like you are supposed to

**Screenshots/Video:**
![KINGDOM HEARTS II FINAL MIX_2022-06-17_18-01-46](https://user-images.githubusercontent.com/56032903/174339610-d0f409f5-fe33-477b-bc8a-e6174418dcd7.png)
![KINGDOM HEARTS II FINAL MIX_2022-06-17_18-03-25](https://user-images.githubusercontent.com/56032903/174339628-6b473dc8-7bea-4579-b0c5-f3afc55f14d6.jpg)

**Comment by TopazTK** [comment] 2022-06-18 04:40
Cannot reproduce. Closing.

**Closed by TopazTK** 2022-06-18 04:40 UTC
Labels: Bug

**Comment by Zeswen** [comment] 2022-08-02 20:57
Can reproduce. Already have a file on slot 1 Lv99 Golden Crown, started a new one with Roxas Lv1, Critical mode, All abilities on, chose sword twice, skipping all the cutscenes.

After fighting Setzer and winning in the struggle fight, I end up in a zoomed out Station of Serenity.

**Comment by TopazTK** [comment] 2022-08-03 06:39
Cannot reproduce. Most likely fixed in v3.00. Closing.
