### ISSUE TITLE
Repeating boss fight in KH2

### ISSUE THREAD

**Issue by TapZD** [TopazTK/KH-ReFixed#74] opened 2022-08-13 02:01 UTC
**Re:Fixed Version:**
Newest version

**Game in Question:**
KH2 FM

**Bug Description:**
The Shang yu fight kept repeating itself even after completion. Also when Mickey showed up the gate was restoring HP which was strange.

**Reproduction Steps:**
The fight started as normal until the end where it repeated itself. I restarted the game and the problem still happened and then started kh2 from the normal launcher we were able to finish the fight.

**Comment by TopazTK** [comment] 2022-08-13 19:17
Please, PLEASE, read the Closed Issues before making a new one!
Duplicate of #64, #51, #43, and #55.
Closing.

**Closed by TopazTK** 2022-08-13 19:17 UTC
Labels: Bug
