### ISSUE TITLE
[BUG] KH II Shan-Yu battle repeats endlessly if saved by mickey

### ISSUE THREAD

**Issue by jonen560ti** [TopazTK/KH-ReFixed#51] opened 2022-06-20 00:28 UTC
**Re:Fixed Version:**
1.0.0.2

**Game in Question:**
KH II

**Bug Description:**
When battling Shan-Yu in the first Mulan visit. If you were saved by Mickey at least once during the battle,
The boss restarts from the beginning. The boss music doesn't even restart as this happens. Items are
kept as they were when the boss ended, so this is not like hitting restart on the game over screen either.

**Reproduction Steps:**
With the attached save file, load save 99. Enter the boss battle with Shan-Yu.
Make sure to die and get saved by Mickey at least once during the fight. Then proceed to win the battle. (getting saved by Mickey more than once does not seem to change the outcome). As the screen fades to white after Sora defeats Shan-Yu, 
The boss cutscene restarts as if the player just entered the battle for the first time. 

Re-loading the save and defeating Shan-Yu without getting saved by Mickey makes the game proceed
as intended. I was playing on critical level 1 with no other mods used. The save file was started with 
re:fixed installed and had only ever been played on Refixed 1.0.0.2. 

![KHIIFM](https://user-images.githubusercontent.com/23322131/174506135-4c3d6126-c6a3-41df-9f5a-3cbcf080e0af.png)

**Comment by TopazTK** [comment] 2022-06-20 01:57
Please read the closed issues before making another one.
Dupe of #43.
Already fixed in upcoming v3.00.
Closing.

**Closed by TopazTK** 2022-06-20 01:57 UTC
Labels: Bug

**Comment by jonen560ti** [comment] 2022-06-20 02:10
Sorry about that. I didn't realize it was the same bug from title alone.
