### ISSUE TITLE
[BUG] Feature Request: Support all EU Languages

### ISSUE THREAD

**Issue by EmreXCoded** [TopazTK/KH-ReFixed#21] opened 2022-03-08 14:23 UTC
**Re:Fixed Version:** v2.10

**Game in Question:** Kingdom Hearts II

**Bug Description:** The "Skip Roxas Tutorial" Text/Description is not there when playing on a language thats not English

**Reproduction Steps:** Start the Game with any language thats not English and click on NEW GAME

**Screenshots/Video:** 
![Screenshot_1](https://user-images.githubusercontent.com/40892993/157256281-95c6205f-9c29-482d-b959-ddf985e21ca9.png)

**Explanation:** Replace the Description in every Language with the English Text of the Roxas Skip OR translating the text to the other 4 languages. 

I hope that in some version in the future that this is supported.

**Comment by TopazTK** [comment] 2022-03-08 22:14
Duplicate of #16
Closing.

**Closed** 2022-03-08 22:14 UTC
Labels: Bug
