### ISSUE TITLE
[BUG] Audio Problem

### ISSUE THREAD

**Issue by EmreXCoded** [TopazTK/KH-ReFixed#18] opened 2022-03-05 20:35 UTC
**Re:Fixed Version:** v1.50

**Game in Question:** Kingdom Hearts II

**Bug Description:** Soundvolume of everything randomly drops and goes back up.

**Reproduction Steps:**
Just start and play the game. It randomly appears. 

**Screenshots/Video:**
Here is a unlisted Video. If wanted i can make a new video. In this Video it occured 2 or 3 Times.
https://youtu.be/OF8kIZvkRiw

**Comment by AkiraJkr** [comment] 2022-03-06 00:57
Isn't this...a duplicate of #9?

**Comment by EmreXCoded** [comment] 2022-03-06 01:03
On my Game its not that the audio is not played. 
The Audio is playing but the volume randomly drops and goes back up. 
Idk how to describe it properly since i'm from germany and my english is good enough to talk basic

**Comment by TopazTK** [comment] 2022-03-06 03:05
An issue known with the game, considered to be although not a duplicate, but a sister bug of #9.
Tagging as "Cannot Fix" and closing until further research can take place.

**Closed by TopazTK** 2022-03-06 03:05 UTC
Labels: Bug
