### ISSUE TITLE
[BUG] No sfx in cutscene with dual audio

### ISSUE THREAD

**Issue by Yungdaime** [TopazTK/KH-ReFixed#69] opened 2022-07-31 18:25 UTC
Re:Fixed Version : 2.90

Game in question : Kingdom Hearts 2

Bug description : When I am in a cutscene there is no sfx, only the voice. The bug appeared when I install the dual audio patch with the mod Re:Fixed.

Reproduction steps : I just install the dual audio patch with KHPCPatchManager and I follow all the instruction on the readme. I also have a script for ultrawide support, idk if the script have conflict with the mod.

**Comment by TopazTK** [comment] 2022-08-01 14:10
Could not reproduce. Closing until further notice.

**Closed by TopazTK** 2022-08-01 14:10 UTC
Labels: Bug
